config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "root#index"
  get '/about', to: 'about#index'
  #-------------------------------------Sign in routes ---------------------------------------------
  get 'sign_in', to: 'sessions#signIn'
  post 'login', to: 'sessions#login'
 #-------------------------------------- sign up routes --------------------------------------------- 
  get '/sign_up', to: 'registrations#signUp'  
  post '/sign_up' , to:'registrations#create'
  #-------------------------------------- sessions routes --------------------------------------------- 
  get '/sign_in', to: 'login#signIn' , as: :signIn
  delete '/logout', to: 'sessions#logout'
  #----------------------------------------- users routes --------------------------------------------
  get '/userList' , to: 'users#userList'
  get '/user/edit/:id' ,to: 'users#editPage', as: :user_edit_by_id
  patch '/user/edit/:id' ,to: 'users#edit', as: :edit_user
  delete '/user_delete/:id' , to: 'users#delete', as: :user_delete
  # ---------------------------------------- edit password routes ------------------------------------
  get 'edit_password', to: 'passwords#index'
  patch 'edit_password' , to: 'passwords#edit'
  #----------------------------------- friends routes ------------------------------------------------

  resources :friends


  # get 'add_friends' , to: "friends#add_friend"
  # post 'add_friends' , to: "friends#create"
  get '/show_friends' , to: "friends#show_friends"
  # patch 'edit_friend/:id', to: "friends#update",as: :edit_friend
  # get 'edit_friend/:id', to: "friends#edit"
  # delete 'friends/delete/:id', to: "friends#delete", as: :delete_friend

end

app/models/Current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
belongs_to :user
    validates :email , presence:true 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :friends
    has_secure_password
    validates :email , presence: true, format: {with: /\A[^@\s]{8}+@[^@\s]{8}+\z/ , message:" must have 8 charachters before and after '@' sign"}

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :set_current_user 
    def set_current_user
        if session[:user_id]
            Current.user=User.find_by(id: session[:user_id])
        end
    end

    
    def check_user_session
        redirect_to signIn_path ,alert: "You must be signed in for this action !" if Current.user.nil?
    end
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    def add_friend
        @friend=Friend.new 
    end

    def new 
        @friend=Friend.new 
    end
    def index
        @friends= Friend.where(user_id: session[:user_id])
    end
    def create
        puts "friend:" + get_friend_object.to_s
        friend= Friend.new(get_friend_object)
        if  friend.save
        
    
            flash[:notice]= "user successefully added!"
            redirect_to root_path ,status: 301
        else 
            puts friend.errors.full_messages.to_s
        end
        
    end

    def show_friends
        @friends= Friend.where(user_id: session[:user_id])
    end
    
    def edit
        @friend=Friend.find_by(id: params[:id])

    end

    def update
        @friend=Friend.find_by(id: params[:id])
        if @friend.present?
            @friend.update(get_friend_object)
        end
    end

    def delete 
        @friend = Friend.find_by(id: params[:id])
        @friend.destroy
        redirect_to show_friends_path
    end
    def destroy 
        @friend = Friend.find_by(id: params[:id])
        @friend.destroy
        redirect_to show_friends_path
    end

    private 

    def get_friend_object
        params.require("friend").permit(:first_name,:last_name,:email,:phone,:user_id)
    end
    end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def signIn
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
before_action :check_user_session
    def edit 
        puts "params:" + params.to_s
        if Current.user.update(get_pass_values)
            redirect_to signIn_path ,notice:"password reset successfully !" 
            session[:user_id]=nil
        else
            render :index ,status:400
            puts "errors:" + Current.user.errors.full_messages.to_s
        end
    end
    def index
    end

    private
       def get_pass_values
        params.require(:user).permit(:password,:password_confirmation)
       end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def signUp
        @user = User.new
    end
    def create
        begin
        @user=User.new(user_params)
        @user.save
        if @user.save
            session[:user_id]=@user.id
            flash[:notice]= "user successefully added!"
            redirect_to root_path ,status: 301
            
        else
            render :signUp, status: 422
        end
    rescue  => error
        puts error
    end
    end

    private
    def user_params
        params.require(:user).permit(:username,:email,:password,:password_confirmation)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
 def index
 end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def logout
            session[:user_id]=nil
             flash[:notice]="loged out !"
            redirect_to root_path
    end
    def login
        user= User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
        puts "user " + user.email + " suucessfully loged in !"
        session[:user_id]= user.id
        redirect_to root_path ,notice: "user " + user.email + " suucessfully loged in !"

        else
            puts "faild attempt no user found !" 
            flash[:alert] = "Wrong password or email please try again !"
            render :signIn , status:400
        end
    end
    def signIn
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def userList
        if session[:user_id]
            @user=User.find_by(id: session[:user_id])
            @userList = User.all()
        end
    end

    def edit
        @user = User.find_by(id: params[:id])
        if @user.update(get_new_user_data)
            redirect_to userList_path, notice:"user Updated successefully !"
        else
            render :editPage, status: 400
            p "errors:" + @user.errors.full_messages.to_s
        end
    end
    def editPage
        @user = User.find_by(id: params[:id])

    end
    
    
    def delete
        @user = User.find_by(id: params[:id])
        @user.destroy
        redirect_to userList_path
    end

    private 
    def get_new_user_data
        params.require(:user).permit(:username,:email)
    end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1 class="text-black font-bold text-4xl"> About</h1>

app/views/friends/add_friend.html.erb
<h1> Add A Friend</h1>

<%= form_with model: @friend, url: add_friends_path ,class:"flex  flex-col items-center gap-2" do |form| %>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :first_name,"first name" , class:"" %>
<%= form.text_field :first_name ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :last_name,"last_name" %>
<%= form.text_field :last_name ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :email,"email" %>
<%= form.text_field :email ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :phone,"phone" %>
<%= form.text_field :phone ,class:"" %></div>

<%= form.submit "add friend +", class:"bg-green-300 text-white font-bold px-4 rounded-lg py-1 capitalize text-xs" %>

<%end%>

app/views/friends/edit.html.erb
<h1> Edit Friend </h1>

<%= form_with model: @friend, url:friend_path(@friend)  ,class:"flex  flex-col items-center gap-2" do |form| %>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :first_name,"first name" , class:"" %>
<%= form.text_field :first_name ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :last_name,"last_name" %>
<%= form.text_field :last_name ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :email,"email" %>
<%= form.text_field :email ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :phone,"phone" %>
<%= form.text_field :phone ,class:"" %></div>

<%= form.submit "update friend +", class:"bg-green-300 text-white font-bold px-4 rounded-lg py-1 capitalize text-xs" %>

<%end%>

app/views/friends/index.html.erb
<h1> Friend List </h1>
<div class="w-full flex flex-col items-center">
    <% if @friends%>
<h1 class="text-3xl underline text-[#131213] py-2 "> friends List </h1>
        <table class="w-5/6 border-2 border-gray-300 rounded-full">
            <thead>
                <tr>
                    <% ["first name","last name","email","phone" ].each do |title| %>
                        <th class="w-1/5 border-r-2"> <%= title %> </th>
                    <%end%>
                </tr>
            </thead>
            <tbody>

                        <% @friends.reverse.each do |friend| %>
                        <tr class="w-1/4 border-r-2 text-center bg-gray-200"> 
                        
                                <td class="py-4  border border-gray-300"><%= friend.first_name %>  </td>
                                <td class="py-4  border border-gray-300"><%= friend.last_name %>  </td>
                                <td class="py-4  border border-gray-300"><%= friend.email %>  </td>
                                <td class="py-4  border border-gray-300"><%= friend.phone %>  </td>
                                <td class="py-4  border border-gray-300 flex gap-2 items-center justify-center"> 
                                    <%= link_to "edit",edit_friend_path(friend),class:"px-2 py-0.5 capitalize border-2 border-blue-300 rounded-full bg-orange-300 text-white"%>
                                    /<%= button_to "delete",friend_path(friend),method: :delete,class:"px-2 py-0.5 capitalize border-2 border-blue-300 rounded-full bg-red-400 text-white"%>
                                </td>
                        </tr>
                    <%end%>
        

            </tbody>
        </table>
        <%else%>
        <h1 class="text-center text-3xl w-full h-full flex items-center justify-center mt-12"> You're not signed in please sign in to be able to see the users ! </h1>
    <%end%>
</div>

app/views/friends/new.html.erb
<h1> Add A Friend</h1>

<%= form_with model: @friend, url: friends_path ,class:"flex  flex-col items-center gap-2" do |form| %>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :first_name,"first name" , class:"" %>
<%= form.text_field :first_name ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :last_name,"last_name" %>
<%= form.text_field :last_name ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :email,"email" %>
<%= form.text_field :email ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%= form.label :phone,"phone" %>
<%= form.text_field :phone ,class:"" %></div>
<div class="w-1/3 items-center flex justify-between">
<%
=begin%>
 <%= form.label :user_id,"user id" %> 
<%
=end%>
<%= form.text_field :user_id ,value: session[:user_id],class:"" %></div>

<%= form.submit "add friend +", class:"bg-green-300 text-white font-bold px-4 rounded-lg py-1 capitalize text-xs" %>

<%end%>

app/views/friends/show_friends.html.erb
<h1> Friend List </h1>
<div class="w-full flex flex-col items-center">
    <% if @friends%>
<h1 class="text-3xl underline text-[#131213] py-2 "> friends List </h1>
        <table class="w-5/6 border-2 border-gray-300 rounded-full">
            <thead>
                <tr>
                    <% ["first name","last name","email","phone" ].each do |title| %>
                        <th class="w-1/5 border-r-2"> <%= title %> </th>
                    <%end%>
                </tr>
            </thead>
            <tbody>

                        <% @friends.reverse.each do |friend| %>
                        <tr class="w-1/4 border-r-2 text-center bg-gray-200"> 
                        
                                <td class="py-4  border border-gray-300"><%= friend.first_name %>  </td>
                                <td class="py-4  border border-gray-300"><%= friend.last_name %>  </td>
                                <td class="py-4  border border-gray-300"><%= friend.email %>  </td>
                                <td class="py-4  border border-gray-300"><%= friend.phone %>  </td>
                                <td class="py-4  border border-gray-300 flex gap-2 items-center justify-center"> 
                                    <%= link_to "edit","/edit_friend/#{friend.id}",class:"px-2 py-0.5 capitalize border-2 border-blue-300 rounded-full bg-orange-300 text-white"%>
                                    /<%= button_to "delete","friends/delete/#{friend.id}",method: :delete,class:"px-2 py-0.5 capitalize border-2 border-blue-300 rounded-full bg-red-400 text-white"%>
                                </td>
                        </tr>
                    <%end%>
        

            </tbody>
        </table>
        <%else%>
        <h1 class="text-center text-3xl w-full h-full flex items-center justify-center mt-12"> You're not signed in please sign in to be able to see the users ! </h1>
    <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<%= render 'components/navbar' %>

    <main class="container mx-auto mt-28 px-5 flex flex-col w-11/12">
      <%= yield %>
    </main>
  </body>
</html>

app/views/root/index.html.erb
<div class="flex flex-col">
<br/>
<%if flash[:notice]%>
<h1 class="bg-green-400 py-2 px-24 rounded-lg my-2 mx-auto shadow-lg text-white border border-green-500 capitaliwe font-bold"><%= flash[:notice] %> </h1>
<%end%>
<%
=begin%>
 <h1 class="text-white bg-blue-500 font-bold block"> hello there this is my first program</h1> 
<%
=end%>

<img src="https://d2gbo5uoddvg5.cloudfront.net/images/modules/logigroup-logo-footer.png"/>


</div>

app/views/users/editPage.html.erb

<div class=" flex flex-col gap-12 items-center justify-center w-full lg:w-6/12 mx-auto border border border-gray-500 rounded-xl py-8 shadow-md bg-gradient-to-r from-gray-500 to-[#93deff]">
<h1 class="capitalize font-bold text-[#f7f7f7] text-3xl font-sans"> Edit user </h1>
<%= form_with  model: @user,url:edit_user_path,method: :patch ,class:"flex flex-col gap-4" do |form|%>

    <div class="flex justify-between ">
    <%= form.label :username,"Username:" ,class:"text-[#f7f7f7] text-md "%>
    <%= form.text_field :username ,class:"py-0 border border-blue-300 rounded-md"%>
</div>
    <div class="flex justify-between">
 <%= form.label :email,"Email:",class:"text-[#f7f7f7] text-md "%> 

    <%= form.text_field :email, class:"py-0 border border-blue-300 rounded-md"%>
    </div>



    <%= form.submit "update",class:"capitalize text-white px-4 py-1 rounded-lg border border-white w-fit mx-auto "%>
<%= render 'components/form_errors', form: form %>
<%end%>

</div>

app/views/users/userList.html.erb
<div class="w-full flex flex-col items-center">
    <% if @userList%>
<h1 class="text-3xl underline text-[#131213] py-2 "> Users List </h1>
        <table class="w-5/6 border-2 border-gray-300 rounded-full">
            <thead>
                <tr>
                    <% ["id","email", "username","affectation date","action" ].each do |title| %>
                        <th class="w-1/5 border-r-2"> <%= title %> </th>
                    <%end%>
                </tr>
            </thead>
            <tbody>

                        <% @userList.reverse.each do |user| %>
                        <tr class="w-1/4 border-r-2 text-center <%= user.id == session[:user_id] ? 'bg-green-300': 'bg-gray-200'%>"> 
                        
                                <td class="py-4  border border-gray-300"><%= user.id %>  </td>
                                <td class="py-4  border border-gray-300"><%= user.email %>  </td>
                                <td class="py-4  border border-gray-300"><%= user.username %>  </td>
                                <td class="py-4  border border-gray-300"><%= user.created_at %>  </td>
                                <td class="py-4  border border-gray-300 flex gap-2 items-center justify-center"> 
                                    <%= link_to "edit",user_edit_by_id_path("#{user.id}"),class:"px-2 py-0.5 capitalize border-2 border-blue-300 rounded-full bg-orange-300 text-white"%>
                                    /<%= button_to "delete",user_delete_path("#{user.id}"),method: :delete,data: { confirm: "test"},class:"px-2 py-0.5 capitalize border-2 border-blue-300 rounded-full bg-red-400 text-white"%>
                                </td>
                        </tr>
                    <%end%>
        

            </tbody>
        </table>
        <%else%>
        <h1 class="text-center text-3xl w-full h-full flex items-center justify-center mt-12"> You're not signed in please sign in to be able to see the users ! </h1>
    <%end%>
</div>